name: .NET Build And Test

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop"]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  

    env:
      Solution_Name: ../Domain.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: eTicketTests/eTicketTests.csproj      # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      DOTNET_VERSION: 8.0.x                           # Replace with the .NET version you want to use, i.e. 5.0.x. 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Install Dependencies 
      run:  dotnet restore $env:Solution_Name

      # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --configuration $env:Configuration --no-build
  
    

